version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: npminstall.sh
      runas: root
  ApplicationStart:
    - location: npmstart.sh
      runas: root
