version: 0.2

phases:
  install:
    commands:
        - sudo add-apt-repository ppa:deadsnakes/ppa
        - sudo apt-get update
        - sudo apt-get install python3.6 -y
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - sudo python3.6 get-pip.py
        - sudo apt-get install python3.6-venv
        - python3.6 -m venv flask
        - cd flask
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - . bin/activate
      - pip3 install flask
      - python3.6 -m test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
