version: 0.2

phases:
  install:
    commands:
        - sudo add-apt-repository ppa:deadsnakes/ppa
        - sudo apt-get update
        - sudo apt-get install python3.6 -y
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - sudo python3.6 get-pip.py
        - sudo apt-get install python3.6-venv
        - sudo npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - npm start
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
