version: 0.2

phases:
  install:
    commands:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
      - base-directory: 'dist'
      - discard-paths: no
